### ISSUE TITLE
Problem with init()

### ISSUE THREAD

**Issue by Leekao** [peihsinsu/bigquery#1]
my code fails on init() with "TypeError: Cannot read property 'client_email' of undefined" .
both files (PEM & JSON) are there and have correct values.
please advise.

**Comment by peihsinsu** [comment]
About 2015Q1 end, google start to deprecate the client_secret file download. Currently the json file that provided by the web console is not the client_secret file before.  You can change the init method like this:

bq.init({
  client_email: 'your-client-email@developer.gserviceaccount.com',
  key_pem: '/path-to-key.pem'
});

**Comment by Leekao** [comment]
worked perfectly, thanks for the quick reply man!!
